const bridge = window.AstrBotPluginPage;
const preview = !bridge;
const $ = id => document.getElementById(id);
const THEME_KEY = "subscription-ledger-theme";
let theme = "dark";
try { if (localStorage.getItem(THEME_KEY) === "light") theme = "light"; } catch (_) {}
function applyTheme() {
  document.documentElement.dataset.theme = theme;
  const label = theme === "dark" ? "切换到浅色模式" : "切换到深色模式";
  const button = $("theme-toggle");
  button.textContent = theme === "dark" ? "☀ 浅色" : "☾ 深色";
  button.setAttribute("aria-label", label);
  button.title = label;
  document.querySelector('meta[name="theme-color"]').content = theme === "dark" ? "#111513" : "#eef1ea";
}
applyTheme();
const grid = $("items"), form = $("form"), settingsForm = $("settings-form");
const ownerSelect = $("owner");
const SYMBOL = {CNY:"¥",USD:"$",HKD:"HK$",SGD:"S$",EUR:"€",JPY:"¥",GBP:"£"};
const PAYMENT = {unknown:"未记录",alipay:"支付宝",wechat:"微信支付",bank_card:"银行卡",credit_card:"信用卡",paypal:"PayPal",apple_pay:"Apple Pay",google_pay:"Google Pay",other:"其它"};
const DOMAINS = [[/chatgpt|openai/i,"openai.com"],[/spotify/i,"spotify.com"],[/netflix/i,"netflix.com"],[/youtube/i,"youtube.com"],[/icloud|apple/i,"apple.com"],[/adobe|lightroom/i,"adobe.com"],[/crunchyroll/i,"crunchyroll.com"],[/github/i,"github.com"]];
const PALETTES = [["#a6edce","#13251d"],["#e7a4ff","#291532"],["#98b9ff","#16254a"],["#f9bd9b","#3e2016"],["#c8f343","#1a250b"],["#9fd9df","#18343a"]];
let settings = {storage_scope:"separate",reminder_owner_key:"demo",timezone:"server",currency_mode:"separate",base_currency:"CNY",theme:"dark"};
let owners = [], items = [], summary = {}, fx = null, currentOwner = "", activeFilter = "all", activeCategory = "全部", editingId = null, deletingItem = null, serverToday = "";
let toastTimer;

const sample = [
  {id:"demo-1",name:"Spotify Premium",amount:"28.00",currency:"CNY",cycle_months:1,renewal_mode:"auto",status:"active",days:9,reminder_days:3,notes:"个人版",service_domain:"spotify.com",category:"影音娱乐",payment_method:"alipay",payment_other:"",reminder_enabled:1,reminder_mode:"both",is_trial:0,trial_end_date:"",icon_url:""},
  {id:"demo-2",name:"ChatGPT Plus",amount:"20.00",currency:"USD",cycle_months:1,renewal_mode:"auto",status:"active",days:21,reminder_days:5,notes:"",service_domain:"openai.com",category:"AI 工具",payment_method:"credit_card",payment_other:"",reminder_enabled:1,reminder_mode:"before",is_trial:0,trial_end_date:"",icon_url:""},
  {id:"demo-3",name:"iCloud+",amount:"21.00",currency:"CNY",cycle_months:1,renewal_mode:"auto",status:"active",days:13,reminder_days:3,notes:"",service_domain:"apple.com",category:"云服务",payment_method:"apple_pay",payment_other:"",reminder_enabled:1,reminder_mode:"day",is_trial:1,trial_end_date:"",icon_url:""},
  {id:"demo-4",name:"Lightroom",amount:"148.00",currency:"CNY",cycle_months:12,renewal_mode:"manual",status:"paused",days:72,reminder_days:7,notes:"摄影",service_domain:"adobe.com",category:"生产力",payment_method:"unknown",payment_other:"",reminder_enabled:0,reminder_mode:"before",is_trial:0,trial_end_date:"",icon_url:""},
];

function el(tag, className="", value) { const node=document.createElement(tag); if(className)node.className=className; if(value!==undefined)node.textContent=value; return node; }
function toast(message,error=false) { clearTimeout(toastTimer); const box=$("toast"); box.textContent=message; box.classList.toggle("error",error); box.hidden=!message; if(message) toastTimer=setTimeout(()=>box.hidden=true,error?6000:3500); }
function isoToday() { if(settings.timezone==="server") return serverToday || new Date().toLocaleDateString("sv-SE"); return new Intl.DateTimeFormat("sv-SE",{timeZone:settings.timezone,year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date()); }
function addDays(iso,days) { const d=new Date(`${iso}T00:00:00Z`); d.setUTCDate(d.getUTCDate()+days); return d.toISOString().slice(0,10); }
function daysUntil(iso) { return iso?Math.round((Date.parse(`${iso}T00:00:00Z`)-Date.parse(`${isoToday()}T00:00:00Z`))/86400000):Infinity; }
function nextDue(item) { const anchor=item.renewal_date; if(!anchor)return null; if(!Number(item.cycle_months))return anchor>=isoToday()?anchor:null; const [year,month,day]=anchor.split("-").map(Number), [ty,tm]=isoToday().split("-").map(Number); let count=Math.max(0,Math.floor(((ty-year)*12+tm-month)/Number(item.cycle_months))); for(let i=0;i<4;i++,count++){const first=new Date(Date.UTC(year,month-1+count*Number(item.cycle_months),1)); const y=first.getUTCFullYear(),m=first.getUTCMonth()+1,last=new Date(Date.UTC(y,m,0)).getUTCDate(); const result=`${y}-${String(m).padStart(2,"0")}-${String(Math.min(day,last)).padStart(2,"0")}`;if(result>=isoToday())return result;}return null; }
function money(amount,currency) { return `${SYMBOL[currency]||currency+" "}${Number(amount).toLocaleString("zh-CN",{minimumFractionDigits:2,maximumFractionDigits:2})}`; }
function cycleLabel(months) {return ({0:"单次",1:"每月",3:"每季度",6:"每半年",12:"每年"})[months]||`${months} 个月`;}
function markFor(name) {return [...name.trim()].slice(0,2).join("").toUpperCase()||"✳";}
function paletteFor(name) {let hash=0;for(const c of name)hash=(hash*31+c.charCodeAt(0))>>>0;return PALETTES[hash%PALETTES.length];}
function inferredDomain(item) {return item.service_domain || DOMAINS.find(([pattern])=>pattern.test(item.name))?.[1] || "";}
function ownedScope() {return settings.storage_scope==="unified"?"__shared__":currentOwner;}
function demoSummary() {const result={};for(const item of items){if(item.status!=="active"||Number(item.cycle_months)===0||item.trial_active)continue;const yearly=Number(item.amount)*12/Number(item.cycle_months);const bucket=result[item.currency]??={monthly:0,yearly:0};bucket.monthly+=yearly/12;bucket.yearly+=yearly;}return result;}
function totals() {return preview?demoSummary():summary;}
function renderTotals() {
  const all=totals(), currencies=Object.keys(all).sort(), lines=$("monthly-totals"); lines.replaceChildren();
  const converted=settings.currency_mode==="convert" && currencies.every(c=>c===settings.base_currency||fx?.rates?.[c]?.rate);
  if(converted && currencies.length){let month=0,year=0;for(const c of currencies){const rate=c===settings.base_currency?1:Number(fx.rates[c].rate);month+=Number(all[c].monthly)/rate;year+=Number(all[c].yearly)/rate;}const line=el("div","total-line");line.append(el("strong","",money(month,settings.base_currency)),el("small","",settings.base_currency));lines.append(line);$("yearly-totals").textContent=`${money(year,settings.base_currency)} ${settings.base_currency}`;const dates=Object.values(fx?.rates||{}).map(x=>x.date);$("fx-caption").textContent=`参考汇率估算 · ${dates.length?dates.sort()[0]:"原币种"} · 实际扣款以账单为准`;}
  else {if(!currencies.length)lines.append(el("strong","","—"));for(const c of currencies){const line=el("div","total-line");line.append(el("strong","",money(all[c].monthly,c)),el("small","",c));lines.append(line);}$("yearly-totals").textContent=currencies.length?currencies.map(c=>`${money(all[c].yearly,c)} ${c}`).join(" / "):"—";$("fx-caption").textContent=settings.currency_mode==="convert"&&currencies.length?"汇率暂不可用，已按币种分别展示":"按币种分别展示 · 试用与暂停项目不计入";}
}
async function loadFx() {fx=null;if(settings.currency_mode!=="convert"){renderTotals();return;}const quotes=Object.keys(totals()).filter(c=>c!==settings.base_currency);if(!quotes.length){renderTotals();return;}try{fx=preview?null:await bridge.apiGet("fx",{base:settings.base_currency,quotes:quotes.join(",")});}catch(error){toast(error.message,true);}renderTotals();}
function action(label,className,handler) {const b=el("button",className,label);b.type="button";b.addEventListener("click",handler);return b;}
async function setLogo(logo,item) {
  async function tryImage(src){const img=new Image();img.alt="";img.decoding="async";img.referrerPolicy="no-referrer";const loaded=await new Promise(resolve=>{img.onload=()=>resolve(true);img.onerror=()=>resolve(false);img.src=src;});if(loaded&&logo.isConnected){logo.replaceChildren(img);return true;}return false;}
  if(item.icon_url && /^https?:\/\//i.test(item.icon_url) && await tryImage(item.icon_url)) return;
  const domain=inferredDomain(item);if(!domain)return;
  try{const src=preview?`https://logo.debounce.com/${domain}`:(await bridge.apiGet("logo",{domain})).data_url;if(src)await tryImage(src);}catch{}
}
function makeCard(item,index) {
  const card=el("article",`sub-card${item.status==="paused"?" is-paused":""}`), color=el("div","card-color"), [bg,ink]=paletteFor(item.name);color.style.setProperty("--card-color",bg);color.style.setProperty("--card-ink",ink);color.dataset.watermark=markFor(item.name);
  const head=el("div","card-head"), logo=el("div","service-logo",markFor(item.name));head.append(logo,el("span","card-number",`NO. ${String(index+1).padStart(2,"0")}`));color.append(head,el("h3","card-title",item.name));
  const body=el("div","card-detail"), price=el("div","card-price");price.append(el("strong","",money(item.amount,item.currency)),el("small","",`${item.currency} / ${cycleLabel(item.cycle_months)}`));
  const chips=el("div","chips");if(item.category)chips.append(el("span","chip category",item.category));chips.append(el("span",`chip ${item.renewal_mode}`,item.renewal_mode==="auto"?"↻ 自动续费":"手动续费"));if(item.payment_method&&item.payment_method!=="unknown")chips.append(el("span","chip payment",item.payment_method==="other"?item.payment_other:PAYMENT[item.payment_method]||item.payment_method));if(item.trial_active)chips.append(el("span","chip trial",`试用至 ${item.trial_end_date}`));if(item.status==="paused")chips.append(el("span","chip paused","已暂停"));if(!Number(item.reminder_enabled))chips.append(el("span","chip muted","提醒关闭"));
  const meta=el("div","card-meta",item.reminder_enabled?"提醒已开":"不提醒");
  const bottom=el("div","card-bottom"), days=daysUntil(item.trial_active?item.trial_end_date:item.next_due_date), due=el("span",days<=30&&item.status==="active"?"soon":"");due.append(document.createTextNode(item.trial_active?"试用结束 ":"下次续费 "),el("b","",item.trial_active?item.trial_end_date:(item.next_due_date||"—")));const buttons=el("div","card-actions");buttons.append(action("编辑","",()=>openEditor(item)),action(item.status==="paused"?"启用":"暂停","",()=>toggleStatus(item)),action("删除","danger",()=>askDelete(item)));bottom.append(due,buttons);body.append(price,chips,meta,bottom);card.append(color,body);setLogo(logo,item);return card;
}
function renderCategories() {const wrap=$("category-filters"), categories=["全部",...new Set(items.map(x=>x.category).filter(Boolean))];if(!categories.includes(activeCategory))activeCategory="全部";wrap.replaceChildren();for(const cat of categories){const button=action(cat,cat===activeCategory?"active":"",()=>{activeCategory=cat;render();});button.setAttribute("aria-pressed",String(cat===activeCategory));wrap.append(button);}}
function render() {
  renderCategories();const active=items.filter(x=>x.status==="active"), upcoming=active.filter(x=>x.next_due_date).sort((a,b)=>a.next_due_date.localeCompare(b.next_due_date));$("count").textContent=String(active.length).padStart(2,"0");$("upcoming-count").textContent=String(upcoming.filter(x=>daysUntil(x.next_due_date)<=30).length).padStart(2,"0");$("trial-count").textContent=String(active.filter(x=>x.trial_active).length).padStart(2,"0");$("nearest-name").textContent=upcoming[0]?.name||"暂无";$("nearest").textContent=upcoming[0]?.next_due_date||"—";renderTotals();
  const query=$("search").value.trim().toLocaleLowerCase("zh-CN"), visible=items.filter(x=>{if(query&&!(x.name+" "+x.category+" "+x.notes).toLocaleLowerCase("zh-CN").includes(query))return false;if(activeCategory!=="全部"&&x.category!==activeCategory)return false;if(activeFilter==="paused")return x.status==="paused";if(activeFilter==="trial")return x.trial_active&&x.status==="active";if(activeFilter==="soon")return x.status==="active"&&x.next_due_date&&daysUntil(x.next_due_date)<=30;return true;});
  const sort=$("sort").value;visible.sort((a,b)=>sort==="name"?a.name.localeCompare(b.name,"zh-CN"):sort==="amount"?Number(b.amount)-Number(a.amount):(a.next_due_date||"9999").localeCompare(b.next_due_date||"9999")||a.name.localeCompare(b.name,"zh-CN"));$("visible-count").textContent=`${visible.length} 项`;$("hint").textContent=`显示 ${visible.length} / ${items.length} 项`;grid.replaceChildren();if(!visible.length){const box=el("div","empty");box.append(el("span","empty-mark","✳"),el("strong","",items.length?"没有匹配的订阅":"从第一项订阅开始"),el("p","",items.length?"换个关键词或标签试试。":"私聊 Bot 发送 /订阅 绑定提醒会话，然后在这里添加。"));grid.append(box);}else visible.forEach((x,i)=>grid.append(makeCard(x,i)));
}
function updateScopeUI() {$("scope-label").textContent=settings.storage_scope==="unified"?"统一账本":"分账户账本";$("owner-wrap").hidden=settings.storage_scope==="unified";$("timezone-caption").textContent=settings.timezone==="server"?"提醒时区 · 跟随服务器":`提醒时区 · ${settings.timezone}`;$("currency-mode").value=settings.currency_mode;$("base-currency").value=settings.base_currency;$("base-wrap").hidden=settings.currency_mode!=="convert";}
async function refreshOwners() {if(preview){render();return;}const response=await bridge.apiGet("owners");owners=response.owners||[];ownerSelect.replaceChildren(new Option("选择已绑定账户",""));$("reminder-owner").replaceChildren(new Option("尚未绑定私聊",""));for(const o of owners){ownerSelect.add(new Option(`${o.label} · ${o.count} 项`,o.owner_key));$("reminder-owner").add(new Option(o.label,o.owner_key));}currentOwner=owners.some(o=>o.owner_key===currentOwner)?currentOwner:owners.some(o=>o.owner_key===settings.selected_owner_key)?settings.selected_owner_key:owners[0]?.owner_key||"";ownerSelect.value=currentOwner;$("reminder-owner").value=settings.reminder_owner_key;await refreshItems();}
async function refreshItems() {if(preview){render();await loadFx();return;}const owner=ownedScope();if(owner){const response=await bridge.apiGet("subscriptions",{owner});items=response.items||[];summary=response.summary||{};}else{items=[];summary={};}render();await loadFx();}
function updateConditionalFields() {const elements=form.elements;const otherCurrency=elements.currency.value==="OTHER",otherPayment=elements.payment_method.value==="other",trial=elements.is_trial.value==="1";$("currency-other-wrap").hidden=!otherCurrency;elements.currency_other.required=otherCurrency;elements.currency_other.disabled=!otherCurrency;$("payment-other-wrap").hidden=!otherPayment;elements.payment_other.required=otherPayment;elements.payment_other.disabled=!otherPayment;$("trial-end-wrap").hidden=!trial;elements.trial_end_date.required=trial;elements.trial_end_date.disabled=!trial;const reminding=elements.reminder_enabled.value==="1";$("reminder-mode-wrap").hidden=!reminding;$("reminder-days-wrap").hidden=!reminding||elements.reminder_mode.value==="day";}
function openEditor(item=null) {if(!preview&&!ownedScope()){toast("先私聊 Bot 发送 /订阅，绑定提醒会话。",true);return;}editingId=item?.id||null;form.reset();$("form-error").hidden=true;$("form-title").textContent=item?"编辑订阅":"添加订阅";if(item){for(const key of ["name","amount","currency","renewal_date","cycle_months","reminder_days","notes","renewal_mode","status","icon_url","service_domain","category","payment_method","payment_other","reminder_enabled","reminder_mode","is_trial","trial_end_date"])form.elements[key].value=item[key]??"";if(![...form.elements.currency.options].some(x=>x.value===item.currency)){form.elements.currency.value="OTHER";form.elements.currency_other.value=item.currency;}}else form.elements.renewal_date.value=isoToday();updateConditionalFields();$("editor").showModal();form.elements.name.focus();}
function askDelete(item){deletingItem=item;$("delete-name").textContent=item.name;$("delete-dialog").showModal();}
async function confirmDelete(){if(!deletingItem)return;const button=$("delete-confirm");button.disabled=true;try{if(preview)items=items.filter(x=>x.id!==deletingItem.id);else await bridge.apiPost("subscriptions/delete",{owner_key:ownedScope(),id:deletingItem.id});$("delete-dialog").close();deletingItem=null;await refreshOwners();toast("订阅已删除。");}catch(error){toast(error.message,true);}finally{button.disabled=false;}}
async function toggleStatus(item){const status=item.status==="paused"?"active":"paused";try{if(preview){item.status=status;render();}else{await bridge.apiPost("subscriptions/save",{owner_key:ownedScope(),id:item.id,status});await refreshItems();}toast(status==="paused"?"已暂停订阅。":"已启用订阅。");}catch(error){toast(error.message,true);}}
function setFilter(value){activeFilter=value;for(const key of ["all","soon","trial","paused"]){const b=$(`filter-${key}`);b.classList.toggle("active",key===value);b.setAttribute("aria-pressed",String(key===value));}render();}
function exportData(){const allowed=["id","name","amount","currency","renewal_date","cycle_months","renewal_mode","status","payment_method","payment_other","category","notes","reminder_enabled","reminder_mode","reminder_days","is_trial","trial_end_date","service_domain","icon_url","created_at"];const data={format:"astrbot-subscription-ledger",version:1,exported_at:new Date().toISOString(),scope:settings.storage_scope,subscriptions:items.map(item=>Object.fromEntries(allowed.filter(key=>key in item).map(key=>[key,item[key]])))};const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:"application/json"}));const link=el("a");link.href=url;link.download=`subscription-ledger-${isoToday()}.json`;document.body.append(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);toast(`已导出 ${items.length} 项订阅。`);}

form.addEventListener("submit",async event=>{event.preventDefault();const button=$("save"),errorBox=$("form-error");button.disabled=true;errorBox.hidden=true;const data=Object.fromEntries(new FormData(form).entries());if(data.currency==="OTHER")data.currency=data.currency_other.toUpperCase();delete data.currency_other;data.owner_key=ownedScope();if(editingId)data.id=editingId;try{if(preview){const item={...data,id:editingId||`demo-${Date.now()}`,cycle_months:Number(data.cycle_months),reminder_days:Number(data.reminder_days),reminder_enabled:Number(data.reminder_enabled),is_trial:Number(data.is_trial)};item.next_due_date=nextDue(item);item.trial_active=Boolean(item.is_trial&&item.trial_end_date>=isoToday());items=editingId?items.map(x=>x.id===editingId?item:x):[item,...items];}else await bridge.apiPost("subscriptions/save",data);$("editor").close();await refreshOwners();toast(editingId?"订阅已更新。":"订阅已添加。");}catch(error){errorBox.textContent=error.message;errorBox.hidden=false;}finally{button.disabled=false;}});
settingsForm.addEventListener("submit",async event=>{event.preventDefault();const button=$("settings-save");button.disabled=true;const data=Object.fromEntries(new FormData(settingsForm).entries());delete data.owner;try{settings=preview?{...settings,...data}:(await bridge.apiPost("settings",data)).settings;$("settings-dialog").close();updateScopeUI();await refreshOwners();toast("设置已保存。");}catch(error){toast(error.message,true);}finally{button.disabled=false;}});
$("add-top").addEventListener("click",()=>openEditor());$("close").addEventListener("click",()=>$("editor").close());$("cancel").addEventListener("click",()=>$("editor").close());$("delete-cancel").addEventListener("click",()=>$("delete-dialog").close());$("delete-confirm").addEventListener("click",confirmDelete);$("open-settings").addEventListener("click",()=>{for(const key of ["storage_scope","reminder_owner_key","timezone"])settingsForm.elements[key].value=settings[key];ownerSelect.value=currentOwner;$("owner-wrap").hidden=settings.storage_scope==="unified";$("settings-dialog").showModal();});$("settings-close").addEventListener("click",()=>$("settings-dialog").close());$("settings-cancel").addEventListener("click",()=>$("settings-dialog").close());settingsForm.elements.storage_scope.addEventListener("change",()=>$("owner-wrap").hidden=settingsForm.elements.storage_scope.value==="unified");ownerSelect.addEventListener("change",async()=>{currentOwner=ownerSelect.value;try{if(!preview)settings=(await bridge.apiPost("settings",{selected_owner_key:currentOwner})).settings;await refreshItems();}catch(error){toast(error.message,true);}});
$("theme-toggle").addEventListener("click",async()=>{
  const previous=theme, button=$("theme-toggle");theme=theme==="dark"?"light":"dark";applyTheme();button.disabled=true;
  try{if(preview){settings.theme=theme;try{localStorage.setItem(THEME_KEY,theme);}catch(_){}}else settings=(await bridge.apiPost("settings",{theme})).settings;}
  catch(error){theme=previous;applyTheme();toast(`主题保存失败：${error.message}`,true);}
  finally{button.disabled=false;}
});
$("export").addEventListener("click",exportData);$("search").addEventListener("input",render);$("sort").addEventListener("change",render);for(const key of ["all","soon","trial","paused"])$(`filter-${key}`).addEventListener("click",()=>setFilter(key));for(const key of ["currency","payment_method","is_trial","reminder_enabled","reminder_mode"])form.elements[key].addEventListener("change",updateConditionalFields);
async function saveCurrencySettings(){const changes={currency_mode:$("currency-mode").value,base_currency:$("base-currency").value};try{settings=preview?{...settings,...changes}:(await bridge.apiPost("settings",changes)).settings;updateScopeUI();await loadFx();}catch(error){toast(error.message,true);updateScopeUI();}}
$("currency-mode").addEventListener("change",saveCurrencySettings);$("base-currency").addEventListener("change",saveCurrencySettings);

if(preview){settings.theme=theme;$("preview-note").hidden=false;owners=[{owner_key:"demo",label:"示例账户",count:sample.length}];currentOwner="demo";ownerSelect.replaceChildren(new Option("示例账户","demo"));$("reminder-owner").replaceChildren(new Option("示例账户","demo"));const today=isoToday();items=sample.map(x=>({...x,renewal_date:addDays(today,x.days),trial_end_date:x.is_trial?addDays(today,x.days-5):"",next_due_date:addDays(today,x.days),trial_active:!!x.is_trial}));updateScopeUI();render();}else{try{await bridge.ready();const response=await bridge.apiGet("settings");settings=response.settings;theme=settings.theme==="light"?"light":"dark";applyTheme();serverToday=response.server_today;updateScopeUI();await refreshOwners();}catch(error){toast(`加载失败：${error.message}`,true);updateScopeUI();render();}}
